// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: proto/ticketBooking.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages for Ticket Purchase
type PurchaseTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseTicketRequest) Reset() {
	*x = PurchaseTicketRequest{}
	mi := &file_proto_ticketBooking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseTicketRequest) ProtoMessage() {}

func (x *PurchaseTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticketBooking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseTicketRequest.ProtoReflect.Descriptor instead.
func (*PurchaseTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticketBooking_proto_rawDescGZIP(), []int{0}
}

func (x *PurchaseTicketRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *PurchaseTicketRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PurchaseTicketRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type PurchaseTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Receipt       *Receipt               `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseTicketResponse) Reset() {
	*x = PurchaseTicketResponse{}
	mi := &file_proto_ticketBooking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseTicketResponse) ProtoMessage() {}

func (x *PurchaseTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticketBooking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseTicketResponse.ProtoReflect.Descriptor instead.
func (*PurchaseTicketResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticketBooking_proto_rawDescGZIP(), []int{1}
}

func (x *PurchaseTicketResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PurchaseTicketResponse) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	PricePaid     float64                `protobuf:"fixed64,4,opt,name=pricePaid,proto3" json:"pricePaid,omitempty"`
	Seat          *Seat                  `protobuf:"bytes,5,opt,name=seat,proto3" json:"seat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_proto_ticketBooking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticketBooking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_proto_ticketBooking_proto_rawDescGZIP(), []int{2}
}

func (x *Receipt) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Receipt) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Receipt) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Receipt) GetPricePaid() float64 {
	if x != nil {
		return x.PricePaid
	}
	return 0
}

func (x *Receipt) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_ticketBooking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticketBooking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_ticketBooking_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Messages for Receipt Retrieval
type GetReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReceiptRequest) Reset() {
	*x = GetReceiptRequest{}
	mi := &file_proto_ticketBooking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptRequest) ProtoMessage() {}

func (x *GetReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticketBooking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptRequest.ProtoReflect.Descriptor instead.
func (*GetReceiptRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticketBooking_proto_rawDescGZIP(), []int{4}
}

func (x *GetReceiptRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *Receipt               `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReceiptResponse) Reset() {
	*x = GetReceiptResponse{}
	mi := &file_proto_ticketBooking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptResponse) ProtoMessage() {}

func (x *GetReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticketBooking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptResponse.ProtoReflect.Descriptor instead.
func (*GetReceiptResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticketBooking_proto_rawDescGZIP(), []int{5}
}

func (x *GetReceiptResponse) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

// Messages for View User Seats by Section
type UserSeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AllottedSeat  int32                  `protobuf:"varint,2,opt,name=allottedSeat,proto3" json:"allottedSeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSeat) Reset() {
	*x = UserSeat{}
	mi := &file_proto_ticketBooking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSeat) ProtoMessage() {}

func (x *UserSeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticketBooking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSeat.ProtoReflect.Descriptor instead.
func (*UserSeat) Descriptor() ([]byte, []int) {
	return file_proto_ticketBooking_proto_rawDescGZIP(), []int{6}
}

func (x *UserSeat) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserSeat) GetAllottedSeat() int32 {
	if x != nil {
		return x.AllottedSeat
	}
	return 0
}

type GetUsersBySectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       string                 `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersBySectionRequest) Reset() {
	*x = GetUsersBySectionRequest{}
	mi := &file_proto_ticketBooking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersBySectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersBySectionRequest) ProtoMessage() {}

func (x *GetUsersBySectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticketBooking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersBySectionRequest.ProtoReflect.Descriptor instead.
func (*GetUsersBySectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticketBooking_proto_rawDescGZIP(), []int{7}
}

func (x *GetUsersBySectionRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

type GetUsersBySectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       string                 `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	Users         []*UserSeat            `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersBySectionResponse) Reset() {
	*x = GetUsersBySectionResponse{}
	mi := &file_proto_ticketBooking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersBySectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersBySectionResponse) ProtoMessage() {}

func (x *GetUsersBySectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticketBooking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersBySectionResponse.ProtoReflect.Descriptor instead.
func (*GetUsersBySectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticketBooking_proto_rawDescGZIP(), []int{8}
}

func (x *GetUsersBySectionResponse) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *GetUsersBySectionResponse) GetUsers() []*UserSeat {
	if x != nil {
		return x.Users
	}
	return nil
}

type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       string                 `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	SeatNumber    int32                  `protobuf:"varint,2,opt,name=seatNumber,proto3" json:"seatNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_proto_ticketBooking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticketBooking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_proto_ticketBooking_proto_rawDescGZIP(), []int{9}
}

func (x *Seat) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Seat) GetSeatNumber() int32 {
	if x != nil {
		return x.SeatNumber
	}
	return 0
}

// Messages for User Removal
type RemoveUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRequest) Reset() {
	*x = RemoveUserRequest{}
	mi := &file_proto_ticketBooking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRequest) ProtoMessage() {}

func (x *RemoveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticketBooking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticketBooking_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RemoveUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	RemovedUser   *User                  `protobuf:"bytes,2,opt,name=removedUser,proto3" json:"removedUser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserResponse) Reset() {
	*x = RemoveUserResponse{}
	mi := &file_proto_ticketBooking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserResponse) ProtoMessage() {}

func (x *RemoveUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticketBooking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticketBooking_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoveUserResponse) GetRemovedUser() *User {
	if x != nil {
		return x.RemovedUser
	}
	return nil
}

// Messages for Seat Modification
type UpdateUserSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	NewSeat       *Seat                  `protobuf:"bytes,2,opt,name=newSeat,proto3" json:"newSeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserSeatRequest) Reset() {
	*x = UpdateUserSeatRequest{}
	mi := &file_proto_ticketBooking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSeatRequest) ProtoMessage() {}

func (x *UpdateUserSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticketBooking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSeatRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserSeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticketBooking_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateUserSeatRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserSeatRequest) GetNewSeat() *Seat {
	if x != nil {
		return x.NewSeat
	}
	return nil
}

type UpdateUserSeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedReceipt *Receipt               `protobuf:"bytes,2,opt,name=updatedReceipt,proto3" json:"updatedReceipt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateUserSeatResponse) Reset() {
	*x = UpdateUserSeatResponse{}
	mi := &file_proto_ticketBooking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSeatResponse) ProtoMessage() {}

func (x *UpdateUserSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticketBooking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSeatResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserSeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticketBooking_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateUserSeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateUserSeatResponse) GetUpdatedReceipt() *Receipt {
	if x != nil {
		return x.UpdatedReceipt
	}
	return nil
}

var File_proto_ticketBooking_proto protoreflect.FileDescriptor

const file_proto_ticketBooking_proto_rawDesc = "" +
	"\n" +
	"\x19proto/ticketBooking.proto\x12\rticketBooking\"d\n" +
	"\x15PurchaseTicketRequest\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.ticketBooking.UserR\x04user\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\tR\x02to\"d\n" +
	"\x16PurchaseTicketResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x120\n" +
	"\areceipt\x18\x02 \x01(\v2\x16.ticketBooking.ReceiptR\areceipt\"\x9d\x01\n" +
	"\aReceipt\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12'\n" +
	"\x04user\x18\x03 \x01(\v2\x13.ticketBooking.UserR\x04user\x12\x1c\n" +
	"\tpricePaid\x18\x04 \x01(\x01R\tpricePaid\x12'\n" +
	"\x04seat\x18\x05 \x01(\v2\x13.ticketBooking.SeatR\x04seat\"V\n" +
	"\x04User\x12\x1c\n" +
	"\tfirstName\x18\x01 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\")\n" +
	"\x11GetReceiptRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"F\n" +
	"\x12GetReceiptResponse\x120\n" +
	"\areceipt\x18\x01 \x01(\v2\x16.ticketBooking.ReceiptR\areceipt\"W\n" +
	"\bUserSeat\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.ticketBooking.UserR\x04user\x12\"\n" +
	"\fallottedSeat\x18\x02 \x01(\x05R\fallottedSeat\"4\n" +
	"\x18GetUsersBySectionRequest\x12\x18\n" +
	"\asection\x18\x01 \x01(\tR\asection\"d\n" +
	"\x19GetUsersBySectionResponse\x12\x18\n" +
	"\asection\x18\x01 \x01(\tR\asection\x12-\n" +
	"\x05users\x18\x02 \x03(\v2\x17.ticketBooking.UserSeatR\x05users\"@\n" +
	"\x04Seat\x12\x18\n" +
	"\asection\x18\x01 \x01(\tR\asection\x12\x1e\n" +
	"\n" +
	"seatNumber\x18\x02 \x01(\x05R\n" +
	"seatNumber\")\n" +
	"\x11RemoveUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"e\n" +
	"\x12RemoveUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x125\n" +
	"\vremovedUser\x18\x02 \x01(\v2\x13.ticketBooking.UserR\vremovedUser\"\\\n" +
	"\x15UpdateUserSeatRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12-\n" +
	"\anewSeat\x18\x02 \x01(\v2\x13.ticketBooking.SeatR\anewSeat\"r\n" +
	"\x16UpdateUserSeatResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12>\n" +
	"\x0eupdatedReceipt\x18\x02 \x01(\v2\x16.ticketBooking.ReceiptR\x0eupdatedReceipt2\xec\x03\n" +
	"\x14TicketBookingService\x12_\n" +
	"\x0ePurchaseTicket\x12$.ticketBooking.PurchaseTicketRequest\x1a%.ticketBooking.PurchaseTicketResponse\"\x00\x12S\n" +
	"\n" +
	"GetReceipt\x12 .ticketBooking.GetReceiptRequest\x1a!.ticketBooking.GetReceiptResponse\"\x00\x12h\n" +
	"\x11GetUsersBySection\x12'.ticketBooking.GetUsersBySectionRequest\x1a(.ticketBooking.GetUsersBySectionResponse\"\x00\x12S\n" +
	"\n" +
	"RemoveUser\x12 .ticketBooking.RemoveUserRequest\x1a!.ticketBooking.RemoveUserResponse\"\x00\x12_\n" +
	"\x0eUpdateUserSeat\x12$.ticketBooking.UpdateUserSeatRequest\x1a%.ticketBooking.UpdateUserSeatResponse\"\x00B,Z*github.com/sanjaykishor/rail-connect/protob\x06proto3"

var (
	file_proto_ticketBooking_proto_rawDescOnce sync.Once
	file_proto_ticketBooking_proto_rawDescData []byte
)

func file_proto_ticketBooking_proto_rawDescGZIP() []byte {
	file_proto_ticketBooking_proto_rawDescOnce.Do(func() {
		file_proto_ticketBooking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ticketBooking_proto_rawDesc), len(file_proto_ticketBooking_proto_rawDesc)))
	})
	return file_proto_ticketBooking_proto_rawDescData
}

var file_proto_ticketBooking_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_ticketBooking_proto_goTypes = []any{
	(*PurchaseTicketRequest)(nil),     // 0: ticketBooking.PurchaseTicketRequest
	(*PurchaseTicketResponse)(nil),    // 1: ticketBooking.PurchaseTicketResponse
	(*Receipt)(nil),                   // 2: ticketBooking.Receipt
	(*User)(nil),                      // 3: ticketBooking.User
	(*GetReceiptRequest)(nil),         // 4: ticketBooking.GetReceiptRequest
	(*GetReceiptResponse)(nil),        // 5: ticketBooking.GetReceiptResponse
	(*UserSeat)(nil),                  // 6: ticketBooking.UserSeat
	(*GetUsersBySectionRequest)(nil),  // 7: ticketBooking.GetUsersBySectionRequest
	(*GetUsersBySectionResponse)(nil), // 8: ticketBooking.GetUsersBySectionResponse
	(*Seat)(nil),                      // 9: ticketBooking.Seat
	(*RemoveUserRequest)(nil),         // 10: ticketBooking.RemoveUserRequest
	(*RemoveUserResponse)(nil),        // 11: ticketBooking.RemoveUserResponse
	(*UpdateUserSeatRequest)(nil),     // 12: ticketBooking.UpdateUserSeatRequest
	(*UpdateUserSeatResponse)(nil),    // 13: ticketBooking.UpdateUserSeatResponse
}
var file_proto_ticketBooking_proto_depIdxs = []int32{
	3,  // 0: ticketBooking.PurchaseTicketRequest.user:type_name -> ticketBooking.User
	2,  // 1: ticketBooking.PurchaseTicketResponse.receipt:type_name -> ticketBooking.Receipt
	3,  // 2: ticketBooking.Receipt.user:type_name -> ticketBooking.User
	9,  // 3: ticketBooking.Receipt.seat:type_name -> ticketBooking.Seat
	2,  // 4: ticketBooking.GetReceiptResponse.receipt:type_name -> ticketBooking.Receipt
	3,  // 5: ticketBooking.UserSeat.user:type_name -> ticketBooking.User
	6,  // 6: ticketBooking.GetUsersBySectionResponse.users:type_name -> ticketBooking.UserSeat
	3,  // 7: ticketBooking.RemoveUserResponse.removedUser:type_name -> ticketBooking.User
	9,  // 8: ticketBooking.UpdateUserSeatRequest.newSeat:type_name -> ticketBooking.Seat
	2,  // 9: ticketBooking.UpdateUserSeatResponse.updatedReceipt:type_name -> ticketBooking.Receipt
	0,  // 10: ticketBooking.TicketBookingService.PurchaseTicket:input_type -> ticketBooking.PurchaseTicketRequest
	4,  // 11: ticketBooking.TicketBookingService.GetReceipt:input_type -> ticketBooking.GetReceiptRequest
	7,  // 12: ticketBooking.TicketBookingService.GetUsersBySection:input_type -> ticketBooking.GetUsersBySectionRequest
	10, // 13: ticketBooking.TicketBookingService.RemoveUser:input_type -> ticketBooking.RemoveUserRequest
	12, // 14: ticketBooking.TicketBookingService.UpdateUserSeat:input_type -> ticketBooking.UpdateUserSeatRequest
	1,  // 15: ticketBooking.TicketBookingService.PurchaseTicket:output_type -> ticketBooking.PurchaseTicketResponse
	5,  // 16: ticketBooking.TicketBookingService.GetReceipt:output_type -> ticketBooking.GetReceiptResponse
	8,  // 17: ticketBooking.TicketBookingService.GetUsersBySection:output_type -> ticketBooking.GetUsersBySectionResponse
	11, // 18: ticketBooking.TicketBookingService.RemoveUser:output_type -> ticketBooking.RemoveUserResponse
	13, // 19: ticketBooking.TicketBookingService.UpdateUserSeat:output_type -> ticketBooking.UpdateUserSeatResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_ticketBooking_proto_init() }
func file_proto_ticketBooking_proto_init() {
	if File_proto_ticketBooking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ticketBooking_proto_rawDesc), len(file_proto_ticketBooking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ticketBooking_proto_goTypes,
		DependencyIndexes: file_proto_ticketBooking_proto_depIdxs,
		MessageInfos:      file_proto_ticketBooking_proto_msgTypes,
	}.Build()
	File_proto_ticketBooking_proto = out.File
	file_proto_ticketBooking_proto_goTypes = nil
	file_proto_ticketBooking_proto_depIdxs = nil
}
